#!/usr/bin/env bash

# login
pio account login -u ${PIO_USERNAME} -p ${PIO_PASSWORD}

# clean target
pio remote -a ${PIO_AGENT} run -e due -t clean

# run tests
pio remote -a ${PIO_AGENT} test -e due

# logout when done
pio account logout
